export const EventList=[

    {
        title:'Introduction To GDSC TCET',
        url:'https://gdsc.community.dev/events/details/developer-student-clubs-thakur-college-of-engineering-and-technology-mumbai-presents-event0-introduction-to-gdsc-tcet/',
        date:'5 September 2021',
        imageurl:'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/text40_BOrLVJZ.png',
        description:'Introduction to Google Developer Student club and the core team',
        agenda1:'What is GDSC',
        agenda2:'Various Google Technolgies',
        agenda3:'Upcoming Events',
        agenda4:'QnA',
    },
    {
        title:'Cloud Study Jam',
        url:'https://gdsc.community.dev/events/details/developer-student-clubs-thakur-college-of-engineering-and-technology-mumbai-presents-30daysofgooglecloud-2021-09-27/',
        date:'27 September to October 18',
        imageurl:'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/_Logo_uI4D6qr.png',
        description:'Hands-on practice on Google Cloud - the tool that powers apps like Gmail and YouTube.',
        agenda1:'Introduction to Google Cloud',
        agenda2:'Introduction to Docker',
        agenda3:'Hands on Session with Docker and Kubernetes',
        agenda4:'Load Balancer',
    },
    {
        title:'Tech Talk',
        url:'https://gdsc.community.dev/events/details/developer-student-clubs-thakur-college-of-engineering-and-technology-mumbai-presents-event1-hack-the-hackathon/',
        date:'17 October 2021',
        imageurl:'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/WhatsApp%20Image%202021-10-14%20at%2010.54.16%20PM.jpeg',
        description:'GDSC TCET is now collaborated with NIT Rourkela,HackNITR 3.0',
        agenda1:'Various Speakers Sharing their experience',
        agenda2:'Doubt Clearing for the Hackathon',
        agenda3:'Insights',
        agenda4:'QnA',
    },
]