on:
  push:
    branches: dev
env:
  CI: false
name: 🚀 Deploy dev branch on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: 🔨 Build Project
        run: |
          npm install --force
          npm run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.dev_ftp_username }}
          password: ${{ secrets.dev_ftp_password }}
          dangerous-clean-slate: true
          local-dir: ./build/
